stages:
  - build

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build-and-push:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    # Login to GitLab registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

    # Enable buildx
    - docker buildx create --use
  script:
    - docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t $CI_REGISTRY_IMAGE:$IMAGE_TAG \
        -t $CI_REGISTRY_IMAGE:latest \
        --push .
  only:
    - main